/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/_terminal'
import { Route as TerminalIndexRouteImport } from './routes/_terminal.index'
import { Route as TerminalStrategyLabRouteImport } from './routes/_terminal.strategy-lab'
import { Route as TerminalSignalsRouteImport } from './routes/_terminal.signals'
import { Route as TerminalSettingsRouteImport } from './routes/_terminal.settings'
import { Route as TerminalRiskRouteImport } from './routes/_terminal.risk'
import { Route as TerminalPortfolioRouteImport } from './routes/_terminal.portfolio'
import { Route as TerminalOrdersRouteImport } from './routes/_terminal.orders'
import { Route as TerminalMarketRouteImport } from './routes/_terminal.market'
import { Route as TerminalLogsRouteImport } from './routes/_terminal.logs'
import { Route as TerminalHealthRouteImport } from './routes/_terminal.health'
import { Route as TerminalExplainabilityRouteImport } from './routes/_terminal.explainability'

const TerminalRoute = TerminalRouteImport.update({
  id: '/_terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalIndexRoute = TerminalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalStrategyLabRoute = TerminalStrategyLabRouteImport.update({
  id: '/strategy-lab',
  path: '/strategy-lab',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalSignalsRoute = TerminalSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalSettingsRoute = TerminalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalRiskRoute = TerminalRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalPortfolioRoute = TerminalPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalOrdersRoute = TerminalOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalMarketRoute = TerminalMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalLogsRoute = TerminalLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalHealthRoute = TerminalHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => TerminalRoute,
} as any)
const TerminalExplainabilityRoute = TerminalExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => TerminalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TerminalIndexRoute
  '/explainability': typeof TerminalExplainabilityRoute
  '/health': typeof TerminalHealthRoute
  '/logs': typeof TerminalLogsRoute
  '/market': typeof TerminalMarketRoute
  '/orders': typeof TerminalOrdersRoute
  '/portfolio': typeof TerminalPortfolioRoute
  '/risk': typeof TerminalRiskRoute
  '/settings': typeof TerminalSettingsRoute
  '/signals': typeof TerminalSignalsRoute
  '/strategy-lab': typeof TerminalStrategyLabRoute
}
export interface FileRoutesByTo {
  '/explainability': typeof TerminalExplainabilityRoute
  '/health': typeof TerminalHealthRoute
  '/logs': typeof TerminalLogsRoute
  '/market': typeof TerminalMarketRoute
  '/orders': typeof TerminalOrdersRoute
  '/portfolio': typeof TerminalPortfolioRoute
  '/risk': typeof TerminalRiskRoute
  '/settings': typeof TerminalSettingsRoute
  '/signals': typeof TerminalSignalsRoute
  '/strategy-lab': typeof TerminalStrategyLabRoute
  '/': typeof TerminalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_terminal': typeof TerminalRouteWithChildren
  '/_terminal/explainability': typeof TerminalExplainabilityRoute
  '/_terminal/health': typeof TerminalHealthRoute
  '/_terminal/logs': typeof TerminalLogsRoute
  '/_terminal/market': typeof TerminalMarketRoute
  '/_terminal/orders': typeof TerminalOrdersRoute
  '/_terminal/portfolio': typeof TerminalPortfolioRoute
  '/_terminal/risk': typeof TerminalRiskRoute
  '/_terminal/settings': typeof TerminalSettingsRoute
  '/_terminal/signals': typeof TerminalSignalsRoute
  '/_terminal/strategy-lab': typeof TerminalStrategyLabRoute
  '/_terminal/': typeof TerminalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explainability'
    | '/health'
    | '/logs'
    | '/market'
    | '/orders'
    | '/portfolio'
    | '/risk'
    | '/settings'
    | '/signals'
    | '/strategy-lab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/explainability'
    | '/health'
    | '/logs'
    | '/market'
    | '/orders'
    | '/portfolio'
    | '/risk'
    | '/settings'
    | '/signals'
    | '/strategy-lab'
    | '/'
  id:
    | '__root__'
    | '/_terminal'
    | '/_terminal/explainability'
    | '/_terminal/health'
    | '/_terminal/logs'
    | '/_terminal/market'
    | '/_terminal/orders'
    | '/_terminal/portfolio'
    | '/_terminal/risk'
    | '/_terminal/settings'
    | '/_terminal/signals'
    | '/_terminal/strategy-lab'
    | '/_terminal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TerminalRoute: typeof TerminalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_terminal': {
      id: '/_terminal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_terminal/': {
      id: '/_terminal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TerminalIndexRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/strategy-lab': {
      id: '/_terminal/strategy-lab'
      path: '/strategy-lab'
      fullPath: '/strategy-lab'
      preLoaderRoute: typeof TerminalStrategyLabRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/signals': {
      id: '/_terminal/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof TerminalSignalsRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/settings': {
      id: '/_terminal/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof TerminalSettingsRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/risk': {
      id: '/_terminal/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof TerminalRiskRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/portfolio': {
      id: '/_terminal/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof TerminalPortfolioRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/orders': {
      id: '/_terminal/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof TerminalOrdersRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/market': {
      id: '/_terminal/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof TerminalMarketRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/logs': {
      id: '/_terminal/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof TerminalLogsRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/health': {
      id: '/_terminal/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof TerminalHealthRouteImport
      parentRoute: typeof TerminalRoute
    }
    '/_terminal/explainability': {
      id: '/_terminal/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof TerminalExplainabilityRouteImport
      parentRoute: typeof TerminalRoute
    }
  }
}

interface TerminalRouteChildren {
  TerminalExplainabilityRoute: typeof TerminalExplainabilityRoute
  TerminalHealthRoute: typeof TerminalHealthRoute
  TerminalLogsRoute: typeof TerminalLogsRoute
  TerminalMarketRoute: typeof TerminalMarketRoute
  TerminalOrdersRoute: typeof TerminalOrdersRoute
  TerminalPortfolioRoute: typeof TerminalPortfolioRoute
  TerminalRiskRoute: typeof TerminalRiskRoute
  TerminalSettingsRoute: typeof TerminalSettingsRoute
  TerminalSignalsRoute: typeof TerminalSignalsRoute
  TerminalStrategyLabRoute: typeof TerminalStrategyLabRoute
  TerminalIndexRoute: typeof TerminalIndexRoute
}

const TerminalRouteChildren: TerminalRouteChildren = {
  TerminalExplainabilityRoute: TerminalExplainabilityRoute,
  TerminalHealthRoute: TerminalHealthRoute,
  TerminalLogsRoute: TerminalLogsRoute,
  TerminalMarketRoute: TerminalMarketRoute,
  TerminalOrdersRoute: TerminalOrdersRoute,
  TerminalPortfolioRoute: TerminalPortfolioRoute,
  TerminalRiskRoute: TerminalRiskRoute,
  TerminalSettingsRoute: TerminalSettingsRoute,
  TerminalSignalsRoute: TerminalSignalsRoute,
  TerminalStrategyLabRoute: TerminalStrategyLabRoute,
  TerminalIndexRoute: TerminalIndexRoute,
}

const TerminalRouteWithChildren = TerminalRoute._addFileChildren(
  TerminalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  TerminalRoute: TerminalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
